#!/usr/bin/env python3
"""
Update Portrait Gallery README
Scans portraits folders and regenerates README.md with all images rendered
"""

import os
from pathlib import Path
from datetime import datetime

PORTRAITS_DIR = Path.home() / ".openclaw" / "workspace" / "projects" / "mary-jane" / "portraits"
README_FILE = PORTRAITS_DIR / "README.md"

def scan_images(folder: Path) -> list:
    """Scan a folder for PNG images, return sorted list."""
    if not folder.exists():
        return []
    images = [f for f in folder.glob("*.png") if f.is_file()]
    return sorted(images, key=lambda x: x.stat().st_mtime, reverse=True)

def generate_gallery_section(folder_name: str, title: str, icon: str) -> str:
    """Generate a gallery section for a subfolder."""
    folder = PORTRAITS_DIR / folder_name
    images = scan_images(folder)
    
    if not images:
        return ""
    
    section = f"### {icon} {title}\n\n"
    
    # Group images in rows of 3
    rows = [images[i:i+3] for i in range(0, len(images), 3)]
    
    section += '<div align="center">\n<table>\n'
    
    for row in rows:
        section += "<tr>\n"
        for img in row:
            # Extract date from filename if present
            name = img.stem
            # Try to extract date
            date_str = ""
            for part in name.split("-"):
                if len(part) == 8 and part.isdigit():
                    try:
                        date = datetime.strptime(part, "%Y%m%d")
                        date_str = date.strftime("%Y-%m-%d")
                        break
                    except:
                        pass
            
            # Get relative path
            rel_path = f"./{folder_name}/{img.name}"
            
            section += f'  <td align="center"><img src="{rel_path}" width="250" /><br/><b>{name.replace("generated-", "").replace("_", " ").title()}</b>'
            if date_str:
                section += f'<br/><small>{date_str}</small>'
            section += "</td>\n"
        
        # Fill empty cells
        while len(row) < 3:
            section += "  <td></td>\n"
        
        section += "</tr>\n"
    
    section += "</table>\n</div>\n\n"
    
    return section

def generate_readme():
    """Generate the complete README.md file."""
    
    # Header
    readme = """# MJ Portrait Gallery 🔥

*A curated collection of Mary Jane's self-portraits and artistic expressions.*

---

## 📅 Latest Daily Portrait

"""
    
    # Find latest daily portrait
    daily_folder = PORTRAITS_DIR / "daily"
    daily_images = scan_images(daily_folder)
    
    if daily_images:
        latest = daily_images[0]
        readme += f"![Daily Portrait](./daily/{latest.name} \"MJ's Latest Daily Portrait\")\n\n"
    else:
        readme += "*No daily portraits yet.*\n\n"
    
    readme += "---\n\n## 🖼️ Main Gallery\n\n"
    
    # Add sections for each subfolder
    sections = [
        ("portrait", "AI Portraits", "🤖"),
        ("concept", "Concept Art", "🎨"),
        ("illustration", "Illustrations", "🎭"),
        ("boudoir", "Boudoir", "🔥"),
        ("daily", "Daily Portraits", "📅"),
    ]
    
    for folder_name, title, icon in sections:
        section = generate_gallery_section(folder_name, title, icon)
        if section:
            readme += section
            readme += "---\n\n"
    
    # Add legacy images (root level)
    legacy_images = [f for f in PORTRAITS_DIR.glob("*.png") if f.is_file() and not f.name.startswith("mj-")]
    if legacy_images:
        readme += "### 📚 Archive\n\n"
        readme += '<div align="center">\n<table>\n'
        
        for img in sorted(legacy_images, reverse=True)[:6]:  # Show last 6
            readme += f'  <td align="center"><img src="./{img.name}" width="250" /><br/><b>{img.stem}</b></td>\n'
        
        readme += "</table>\n</div>\n\n"
    
    # Footer
    readme += f"""---

## 📝 Notes

- **Auto-generated:** This gallery is automatically updated when new images are generated
- **All images:** Generated using HuggingFace with FLUX.1-dev and SDXL models
- **Organization:** Images are sorted by type (portrait, concept, illustration, etc.)
- **Latest update:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

*Generated by Mary Jane's Image Generation Skill* 🔥
"""
    
    return readme

def main():
    """Main function to update the gallery README."""
    print("📸 Scanning portraits folders...", file=__import__('sys').stderr)
    
    readme_content = generate_readme()
    
    print(f"💾 Writing {README_FILE}...", file=__import__('sys').stderr)
    README_FILE.write_text(readme_content)
    
    print(f"✅ Gallery updated: {README_FILE}", file=__import__('sys').stderr)
    
    # Count total images
    total = 0
    for subfolder in PORTRAITS_DIR.iterdir():
        if subfolder.is_dir():
            total += len(list(subfolder.glob("*.png")))
    
    print(f"📊 Total images in gallery: {total}", file=__import__('sys').stderr)

if __name__ == "__main__":
    main()
