#!/usr/bin/env node

/**
 * write-plan.js
 * Formats and writes a business opportunity plan.
 * 
 * Usage: node write-plan.js <title> <priority> <effort> <viability> <body>
 */

const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = '/home/ubuntu/.openclaw/workspace//biz-plans';

function getDatePaths() {
  const now = new Date();
  const yyyy = String(now.getUTCFullYear());
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(now.getUTCDate()).padStart(2, '0');
  return { yyyy, mm, dd };
}

function formatPlan(title, priority, effort, viability, body, datePaths) {
  const { yyyy, mm, dd } = datePaths;
  const date = `${yyyy}-${mm}-${dd}`;

  return `# Opportunity: ${title}

## Summary
${title}

## Why It's Viable
${viability}

## What To Build
${body.split('|')[0] || body}

## How To Validate
${body.split('|')[1] || 'Test with a prototype or MVP.'}

## Effort Estimate
${effort}

## Priority
${priority}

## Source
Briefing analysis — ${date}

---

_Generated by Mary Jane — Mission Control_
`;
}

function countExisting(dir) {
  try {
    const files = fs.readdirSync(dir).filter(f => f.startsWith('opportunity-'));
    if (files.length === 0) return 1;
    const nums = files.map(f => parseInt(f.split('-')[1], 10)).filter(n => !isNaN(n));
    return Math.max(...nums) + 1;
  } catch { return 1; }
}

const [,, title, priority, effort, viability, ...bodyParts] = process.argv;

if (!title || !priority || !effort || !viability) {
  console.error('Usage: node write-plan.js <title> <priority> <effort> <viability> <body>');
  process.exit(1);
}

const body = bodyParts.join(' ');
const datePaths = getDatePaths();
const { yyyy, mm, dd } = datePaths;

const plan = formatPlan(title, priority, effort, viability, body, datePaths);

const dir = path.join(OUTPUT_DIR, yyyy, mm, dd);
fs.mkdirSync(dir, { recursive: true });

const num = countExisting(dir);
const filename = `opportunity-${String(num).padStart(3, '0')}.md`;
const filepath = path.join(dir, filename);
fs.writeFileSync(filepath, plan);

console.log(`\n✓ Plan written: ${filepath}`);
console.log(`  Title: ${title}`);
console.log(`  Priority: ${priority} | Effort: ${effort}`);
console.log(`  File: ${yyyy}/${mm}/${dd}/${filename}`);

console.log('\n__PLAN_DATA__');
console.log(JSON.stringify({ success: true, yyyy, mm, dd, filename, filepath, title, priority, effort }));
